### ISSUE TITLE
A few feature requests and improvements

### ISSUE THREAD

**Issue by Tiger21820** [Mike-on-Tour/sudoku#1]
I'm not sure if this is the right place to request features for this extension, and if not, let me know where!

Anyways, I do have a few features and improvements for this extension:

Feature 1, which might probably not be integrated into the extension itself if taken into consideration, but would be nice to have access to one way or another:
The ability to create your own puzzle pack easily! I've actually made my own puzzles by editing the xml files by hand and installed them onto my forum, but it's very tricky and takes a VERY long time to do it manually (Especially a Samurai or Ninja puzzle), and I have NO idea what you did to create your puzzle packs, so if there was an easy way for people to generate xml files of their own puzzles using your mot formats, please make that public! (Also, let me know if you would like to see these puzzles!)

Feature 2: Choosing any installed unsolved puzzle from a list, rather than, or in addition to the extension picking one randomly, since there are nearly 5000 puzzles, and finding your own packs takes a long time unless you modify the sql database!

Feature 3: Abandoning an already started puzzle, or suspending an already started puzzle to solve at a later time, and choosing a different puzzle without having to suffer a negative point penalty (which requires deleting the entry row from the phpbb_mot_sudoku_games table manually) by having to solve a puzzle through digit purchases! This could be done by allowing multiple rows of the same puzzle type by the same user, and the user being able to switch between any of those from a list without any form of a point penalty!

Feature 4: If feature request 2 is accepted, then another feature that can be added provided that solved puzzles are not replayable in the current version is that each solved puzzle has a top score that a user can try to beat if that puzzle was solved with penalties, and since each puzzle has a 'perfect score' as defined by the current score settings, any improved score from any replayed puzzle can be added to a user's overall total score!

An example for this proposed feature:
Classic Puzzle ID 192 (Which could be pack 14, game 3) has a maximum score of 620 points with what the point settings could be configured with, but was solved with a penalty of -192 points resulting in a score of 428 being added to your overall total score and that score being saved to that specific user and puzzle ID as 428 out of 620, and solving it again with no penalties would update that puzzle's high score to 620, and add 192 points to the overall score rather than 620 points! 

Again, if this is not the right place to request features, then I apologize in advance, and let me know where I can request these features for implementation into future versions of this extension! Thank you!

**Comment by Mike-on-Tour** [comment]
Basically "issues" here are code-related, e.g. bugs, so it might be better to discuss support and feature questions on my web page (www.mike-on-tour.com).
Closing here.

**Comment by Tiger21820** [comment]
Then I shall register an account and post my requests there! Thanks for the reply!
